version: 1.0.0-{build}
os: Windows Server 2012 R2
platform: x64
configuration: Release
branches:
  except:
    - coverity_scan
environment:
  matrix:
  - CMAKE_GENERATOR: "NMake Makefiles"
    ARCH: "amd64_x86"
  - CMAKE_GENERATOR: "NMake Makefiles"
    ARCH: "amd64"
install:
  - SET PATH=C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC;%PATH%
  - git clone --quiet https://github.com/OpenMA/openma-data.git data
before_build:
  - vcvarsall %ARCH%
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE:CHAR=%CONFIGURATION% -DBUILD_SHARED_LIBS:BOOL=1 -DBUILD_UNIT_TESTS:BOOL=1 -DOPENMA_TESTING_DATA_PATH:CHAR=C:\projects\openma\data -G "%CMAKE_GENERATOR%" ..
build_script:
  - echo BUILD INFO - %CMAKE_GENERATOR% / %ARCH% / %CONFIGURATION%
  - nmake
test_script:
  - ctest -VV