# The main language used in the project is the C++ language.
# The setting of the language to 'objective-c' is only for travis to know that we want to use
# a MacOS X building environment
language: objective-c

# To prepare the system to install prerequisites or dependencies
before_install:
  - brew update 
  - brew unlink cmake # By default, CMake 3.0 (or less) is used
  
# To install any prerequisites or dependencies necessary to run your build
install:  
  - brew install cmake # And we need at least CMake 3.1 (for the activation of C++11)
  
# To prepare your build for testing
before_script:
  - git clone https://github.com/OpenMA/openma-data.git data

# Compilation of the project and testing
script:
  - ROOT=`pwd`
  - rm -rf build
  - mkdir build
  - cd build
  - if [ "$SELECTED_COMPILER" = "GCC" ]; then export CC=gcc-4.8 && export CXX=g++-4.8; fi
  - if [ ${COVERITY_SCAN_BRANCH} != 1 ]; then cmake -DCMAKE_BUILD_TYPE:CHAR=$WITH_BUILD_TYPE -DBUILD_SHARED_LIBS:BOOL=$WITH_SHARED_LIBS -DWITH_COVERALLS_ENABLED:BOOL=$WITH_COVERALLS_ENABLED -DBUILD_TESTING:BOOL=1 -DOPENMA_TESTING_DATA_PATH:CHAR=$ROOT/data -G "Unix Makefiles" ..; fi
  - if [ ${COVERITY_SCAN_BRANCH} != 1 ]; then make; fi
  - if [ ${COVERITY_SCAN_BRANCH} != 1 ]; then ctest -VV; fi
  
after_success:
  - if [ ${COVERITY_SCAN_BRANCH} != 1 ] && [ ${WITH_COVERALLS_ENABLED} == 1 ]; then make coveralls; fi

# Building matrix used by the 'script' section
env:
  global:
    - secure: ""
  
  matrix:
    - SELECTED_COMPILER=Clang WITH_BUILD_TYPE=Release WITH_SHARED_LIBS=1 WITH_COVERITY_ENABLED=0 WITH_COVERALLS_ENABLED=0
    # - SELECTED_COMPILER=GCC   WITH_BUILD_TYPE=Release WITH_SHARED_LIBS=1 WITH_COVERITY_ENABLED=0 WITH_COVERALLS_ENABLED=0
    # - SELECTED_COMPILER=GCC   WITH_BUILD_TYPE=Release WITH_SHARED_LIBS=0 WITH_COVERITY_ENABLED=0 WITH_COVERALLS_ENABLED=0
    - SELECTED_COMPILER=Clang WITH_BUILD_TYPE=Debug   WITH_SHARED_LIBS=0 WITH_COVERITY_ENABLED=0 WITH_COVERALLS_ENABLED=0
      
matrix:
  # Allow failure for Coverity as this is not a standard compiler (COVERITY_SCAN_BRANCH is defined by the coverity_scan addon)
  allow_failures:
    - env: COVERITY_SCAN_BRANCH=1

# Coverity configuration
addons:
  coverity_scan:
    project:
      name: "OpenMA/openma"
      description: "Build submitted via Travis CI"
    notification_email: arnaud.barre@gmail.com
    build_command_prepend: "export CC=gcc-4.8; export CXX=g++-4.8; cmake -DWITH_COVERITY_ENABLED:BOOL=$WITH_COVERITY_ENABLED .; make clean"
    build_command: "make coverity"
    branch_pattern: coverity_scan