# C++ project
language: cpp

# Built on the following OS
os:
  - osx

# With the following compilers
compiler:
  - clang
  - gcc

# To prepare the system to install prerequisites or dependencies
before_install:
  - brew update 
  
# To prepare your build for testing
before_script:
  - git clone https://github.com/OpenMA/openma-data.git data

# Compilation of the project and testing
script:
  - ROOT=`pwd`
  - rm -rf build
  - mkdir build
  - cd build
  - if [ ${COVERITY_SCAN_BRANCH} != 1 ]; then cmake -DCMAKE_BUILD_TYPE:CHAR=$WITH_BUILD_TYPE -DBUILD_SHARED_LIBS:BOOL=$WITH_SHARED_LIBS -DWITH_COVERALLS_ENABLED:BOOL=$WITH_COVERALLS_ENABLED -DBUILD_UNIT_TESTS:BOOL=1 -DOPENMA_TESTING_DATA_PATH:CHAR=$ROOT/data -G "Unix Makefiles" ..; fi
  - if [ ${COVERITY_SCAN_BRANCH} != 1 ]; then make; fi
  - if [ ${COVERITY_SCAN_BRANCH} != 1 ]; then ctest -VV; fi
  
after_success:
  - if [ ${COVERITY_SCAN_BRANCH} != 1 ] && [ ${WITH_COVERALLS_ENABLED} == 1 ]; then make coveralls; fi

# Building matrix used by the 'script' section
env:
  matrix:
    - WITH_BUILD_TYPE=Debug   WITH_SHARED_LIBS=0 WITH_COVERALLS_ENABLED=1 WITH_COVERITY_ENABLED=0
    - WITH_BUILD_TYPE=Debug   WITH_SHARED_LIBS=1 WITH_COVERALLS_ENABLED=0 WITH_COVERITY_ENABLED=0
    - WITH_BUILD_TYPE=Release WITH_SHARED_LIBS=0 WITH_COVERALLS_ENABLED=0 WITH_COVERITY_ENABLED=1
    - WITH_BUILD_TYPE=Release WITH_SHARED_LIBS=1 WITH_COVERALLS_ENABLED=0 WITH_COVERITY_ENABLED=0
  global:
    - secure: "APbR5MQdBH4haJuend5q07w+gAafhjtT8z7T2JS0ZIepQc+qwWucd6BRvkcD7fMpogEJ6+d55frtSW51Fw9o5h0ioXxx5pXJ/ZMnkDKy0V6oDpghPm2JSO+1wF1S+Xmsbw3fxuSIQAWSJHkkuJZyJAC8Rerg4Pz0XMi4XU0WOtsRhdPk6mJUbmeKu055qbyJRW4EuhamroZLjLwvFkRjbyJ79mfGd4mm7GTrXaG/ImQeq3LW+5qhD8q5ypb7gXIMkal58EAsTi6wEVJIWIGOHS3U2dZ8ZM9doV+hdZJd2zAO8ZHGpFMw9zpdghUsWyXGPuoYJBE71FxZ910vpRtbZ6hba8LkEoLj4SpeT+rpQoXozXtdklMmZQrJp9deQaena8i195PJ8pxXrUpMcOIEIp2IwbTVT2+gbrw5nuFwUjeXkwb61Ng598WQMAMPPJ4suPuWzk+vL1a/ZADntFdPgQ9FxofNz8T21wC3UTk1t4VQsrZsXYedpuP5d32EHMrXGOcDwkW0QTnl/cWnuAnTnUHvhCeV5MmeC1aLXC9yculd/jCnlpTDr2N4T1Ev2DB1AVoN0LRYFU57qwWcb7lDLUT0fEY9quyUxpwLsv4LO0vRaKBNuOkqmvphvmkQLNFwZ1ML9LIy5Eno19DCAAODce668gaJ4ZtaPzbPOqn6B04="
  
matrix:
  exclude:
    - compiler: gcc
      env: WITH_BUILD_TYPE=Debug   WITH_SHARED_LIBS=0 WITH_COVERALLS_ENABLED=1 WITH_COVERITY_ENABLED=0
    - compiler: clang
      env: WITH_BUILD_TYPE=Release WITH_SHARED_LIBS=0 WITH_COVERALLS_ENABLED=0 WITH_COVERITY_ENABLED=1
  # Allow failure for Coverity as this is not a standard compiler (COVERITY_SCAN_BRANCH is defined by the coverity_scan addon)
  allow_failures:
    - env: COVERITY_SCAN_BRANCH=1

# Coverity configuration
addons:
  coverity_scan:
    project:
      name: "OpenMA/openma"
      description: "Build submitted via Travis CI"
    notification_email: arnaud.barre@gmail.com
    build_command_prepend: "export CC=gcc-4.8; export CXX=g++-4.8; cmake -DWITH_COVERITY_ENABLED:BOOL=$WITH_COVERITY_ENABLED .; make clean"
    build_command: "make coverity"
    branch_pattern: coverity_scan