classdef PluginGaitTest < matlab.unittest.TestCase

    methods (Test)
    
        function fixCrashOldRefcountMechanism(testCase)
          calibration_filename = OpenMATDDPathIn('c3d/plugingait/PiG_Calibration-FlatFoot-Hole.c3d');
          dynamic_filename = OpenMATDDPathIn('c3d/plugingait/PiG_Motion-FlatFoot-Hole.c3d');
          subject = ma.Subject('Anonymous', ...
              {{'markerDiameter', 16.0}, ...
               {'leftFootFlatEnabled', true}, ...
               {'leftLegLength', 940.0}, ...
               {'leftKneeWidth', 110.0}, ...
               {'leftAnkleWidth', 70.0}, ...
               {'rightFootFlatEnabled', true}, ...
               {'rightLegLength', 940.0}, ...
               {'rightKneeWidth', 120.0}, ...
               {'rightAnkleWidth', 70.0}});
          skeletonhelper = ma.body.PluginGait(ma.body.Region_Lower, ma.body.Side_Both);
          ma.body.LandmarksTranslator('CGM', ...
                 {{'LASI', 'L.ASIS'}, ...
                  {'RASI', 'R.ASIS'}, ...
                  {'LPSI', 'L.PSIS'}, ...
                  {'RPSI', 'R.PSIS'}, ...
                  {'SACR', 'SC'}, ...
                  {'LTHI', 'L.ITB'}, ...
                  {'RTHI', 'R.ITB'}, ...
                  {'LKNE', 'L.LFE'}, ...
                  {'RKNE', 'R.LFE'}, ...
                  {'LTIB', 'L.LS'}, ...
                  {'RTIB', 'R.LS'}, ...
                  {'LANK', 'L.LTM'}, ...
                  {'RANK', 'R.LTM'}, ...
                  {'LTOE', 'L.MTH2'}, ...
                  {'RTOE', 'R.MTH2'}, ...
                  {'LHEE', 'L.HEE'}, ...
                  {'RHEE', 'R.HEE'}}, skeletonhelper);
          delete(ans);
          trials = ma.io.read(calibration_filename);
          ma.body.calibrate(skeletonhelper, trials, subject);
          models = ma.body.reconstruct(skeletonhelper, trials);
          testCase.verifyEqual(double(trials.child(1).refcount()), 3);
          testCase.verifyEqual(double(models.findChild(ma.T_Trial).refcount()),3)
          testCase.verifyEqual(double(models.findChild(ma.body.T_LandmarksTranslator).refcount()), 3);
          trials = ma.io.read(dynamic_filename);
          models = ma.body.reconstruct(skeletonhelper, trials);
          testCase.verifyEqual(double(trials.child(1).refcount()), 3);
          testCase.verifyEqual(double(models.findChild(ma.T_Trial).refcount()),3)
          testCase.verifyEqual(double(models.findChild(ma.body.T_LandmarksTranslator).refcount()), 3);
          % Crash due to the next line
          models = ma.body.reconstruct(skeletonhelper, trials);
          testCase.verifyEqual(double(trials.child(1).refcount()), 3);
          testCase.verifyEqual(double(models.findChild(ma.T_Trial).refcount()),3)
          testCase.verifyEqual(double(models.findChild(ma.body.T_LandmarksTranslator).refcount()), 3);
          end
          
    end
    
end