STRING(REGEX REPLACE "\\\\ " " " PYTHON_PACKAGE_INIT "${PYTHON_PACKAGE_INIT}") 
STRING(REGEX REPLACE "\\\\n" ";" PYTHON_PACKAGE_INIT "${PYTHON_PACKAGE_INIT}") 
MESSAGE(STATUS "${PYTHON_PACKAGE_INIT}")
CONFIGURE_FILE(
  "${PROJECT_SOURCE_DIR}/cmake/templates/PythonPackageInit.py.in"
  "${PYTHON_PACKAGE_PATH}/__init__.py"
  @ONLY)